# Generated by Django 6.1 on 2026-08-17 20:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIExtraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_text', models.TextField(help_text='Raw text extracted from CV')),
                ('extracted_data', models.JSONField(default=dict, help_text='Structured data extracted by AI')),
                ('model_used', models.CharField(default='mock', help_text='AI model used for extraction', max_length=100)),
                ('status', models.CharField(choices=[('pending_confirmation', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending_confirmation', max_length=50)),
                ('confidence_score', models.FloatField(blank=True, help_text='AI confidence score (0-1)', null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_extractions', to='candidates.candidate')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_extractions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_extractions', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ai_extractions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('extraction', 'Extraction'), ('confirmation', 'Confirmation'), ('rejection', 'Rejection')], max_length=50)),
                ('model_used', models.CharField(max_length=100)),
                ('input_hash', models.CharField(help_text='Hash of input text', max_length=64)),
                ('output_hash', models.CharField(help_text='Hash of extracted data', max_length=64)),
                ('metadata', models.JSONField(default=dict, help_text='Additional metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_audit_logs', to='tenants.tenant')),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ai.aiextraction')),
            ],
            options={
                'db_table': 'ai_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aiextraction',
            index=models.Index(fields=['tenant', 'status'], name='ai_extracti_tenant__9a50da_idx'),
        ),
        migrations.AddIndex(
            model_name='aiextraction',
            index=models.Index(fields=['created_at'], name='ai_extracti_created_c25493_idx'),
        ),
        migrations.AddIndex(
            model_name='aiextraction',
            index=models.Index(fields=['candidate'], name='ai_extracti_candida_ee0b6b_idx'),
        ),
        migrations.AddIndex(
            model_name='aiauditlog',
            index=models.Index(fields=['tenant', 'created_at'], name='ai_audit_lo_tenant__15b7e9_idx'),
        ),
        migrations.AddIndex(
            model_name='aiauditlog',
            index=models.Index(fields=['extraction'], name='ai_audit_lo_extract_9c7945_idx'),
        ),
    ]
