# Generated by Django 6.1 on 2026-08-17 20:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_id', models.IntegerField(db_index=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('READ', 'Read'), ('VERIFY', 'Verify'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EXPORT', 'Export'), ('IMPORT', 'Import')], db_index=True, max_length=10)),
                ('record_type', models.CharField(db_index=True, max_length=50)),
                ('record_id', models.CharField(db_index=True, max_length=36)),
                ('before_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('after_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('data', models.JSONField(default=dict)),
                ('previous_version', models.CharField(blank=True, max_length=36, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='audit_logs_tenant__0b1a88_idx'), models.Index(fields=['record_type', 'record_id'], name='audit_logs_record__7a6c03_idx'), models.Index(fields=['action'], name='audit_logs_action_31f574_idx'), models.Index(fields=['actor_id'], name='audit_logs_actor_i_0badd2_idx'), models.Index(fields=['tenant', 'action'], name='audit_logs_tenant__4c766e_idx')],
            },
        ),
    ]
