# Generated by Django 6.1 on 2026-08-17 20:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('role_applied_for', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='tenants.tenant')),
            ],
            options={
                'db_table': 'candidates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'email'], name='candidates_tenant__61d6c3_idx'), models.Index(fields=['tenant', 'created_at'], name='candidates_tenant__db6fca_idx'), models.Index(fields=['is_active'], name='candidates_is_acti_6ddb6d_idx')],
            },
        ),
    ]
