# Generated by Django 6.1 on 2026-08-17 20:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('right_to_work', 'Right to Work'), ('dbs', 'DBS Check'), ('certification', 'Professional Certification'), ('qualification', 'Qualification'), ('other', 'Other')], max_length=50)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='candidates.candidate')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.compliancedocument')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['candidate', 'is_current'], name='compliance__candida_c723e7_idx'), models.Index(fields=['expiry_date'], name='compliance__expiry__bf6c0d_idx'), models.Index(fields=['status'], name='compliance__status_519e68_idx')],
            },
        ),
    ]
